<a href="https://colab.research.google.com/github/Nagendrareddy777/NLP_tasks/blob/main/Feature_extraction_BagOfWords.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd


In [9]:
doc={"text":["People Watch Campusx","Campusx Watch Campusx","People Write Comment","Campusx Write Comment"],"output":[1,1,0,0]}

In [10]:
df=pd.DataFrame(doc)

In [11]:
df

text  output
0   People Watch Campusx       1
1  Campusx Watch Campusx       1
2   People Write Comment       0
3  Campusx Write Comment       0

In [12]:
from sklearn.feature_extraction.text import CountVectorizer

In [19]:
cv=CountVectorizer()
bow=cv.fit_transform(df["text"])
bow

<4x5 sparse matrix of type '<class 'numpy.int64'>'
	with 11 stored elements in Compressed Sparse Row format>

array([[1, 0, 1, 1, 0]])

In [21]:
cv.vocabulary_

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}

In [22]:
bow[0].toarray()

array([[1, 0, 1, 1, 0]])

In [23]:
bow[1].toarray()

array([[2, 0, 0, 1, 0]])

In [24]:
bow[2].toarray()

array([[0, 1, 1, 0, 1]])

In [25]:
bow[3].toarray()

array([[1, 1, 0, 0, 1]])

In [28]:
cv.transform(["my campusx teaches , write the comment"]).toarray()

array([[1, 1, 0, 0, 1]])